version: '3.8'

services:
  # Development configuration
  frontend-dev:
    container_name: portfolio-website-dev
    restart: unless-stopped
    build: 
      context: .
      target: dev
    image: portfolio-website:dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - BUN_INSTALL_CACHE=/bun/install/cache
    profiles:
      - dev

  # Production configuration
  frontend-prod:
    container_name: portfolio-website
    restart: unless-stopped
    build:
      context: .
      target: prod
    image: itealab/portfolio-website:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles:
      - prod