version: '3.8'

services:
  frontend:
    build:
      context: .
      target: prod
    image: itealab/portfolio-website:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production